### ISSUE TITLE
Mongo uri problem

### ISSUE THREAD

**Issue by Master244** [jasalt/kuittiskanneri#2]
Hi! I dont know if you're example is still working, i'm trying to run it now. Problem is I cannot seem to get the right MONGO_URI. Any suggestions?

app_1   | Traceback (most recent call last):
app_1   |   File "run.py", line 1, in <module>
app_1   |     from app import app
app_1   |   File "/code/app/**init**.py", line 15, in <module>
app_1   |     mongo = PyMongo(app)
app_1   |   File "/usr/local/lib/python2.7/site-packages/flask_pymongo/**init**.py", line 98, in **init**
app_1   |     self.init_app(app, config_prefix)
app_1   |   File "/usr/local/lib/python2.7/site-packages/flask_pymongo/**init**.py", line 230, in init_app
app_1   |     cx = connection_cls(_args, *_kwargs)
app_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 369, in **init**
app_1   |     raise ConnectionFailure(str(e))
app_1   | pymongo.errors.ConnectionFailure: [Errno -2] Name or service not known

while i did create the secrets.py

Any suggestions much appreciated!

**Comment by jasalt** [comment]
Hi, I don't have time to debug this software currently, sorry.

Please double check that you have the MongoDB running properly and are able to get a proper Mongo URI for it. I hope you get it working, and please post if you are able to workaround the problem yourself.

**Comment by AshvinGudaliya** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @PjMpire, @giuliomartinelli, @fabiomen10, @owl4ce, @sdas1503, @namazu510, @greglong83, @tommyliu9, @cbrnrd, @870788541, @artkirienko, @wwkenwong, @alexkab, @QUSIR, @endang121, @eulerlan, @gebv, @playplaya, @notredamedude3, @tomierna
